package com.arguments.functional.requeststate;

/**
 * @author mirleau
 *
 */
public enum ArgsRequestKey{
    THESIS_ID,
    RELATION_ID,
    SET_PERSPECTIVE_ID,
    ADD_PERSPECTIVE_ID,
    REMOVE_PERSPECTIVE_ID,
    PERSPECTIVE2_ID,
    NEW_IF_TRUE_PERCENTAGE_RELEVANCE,
    NEW_IF_FALSE_PERCENTAGE_RELEVANCE,
    NEW_LINK_SOURCE_ID,
    NEW_LINK_TARGET_ID,
    NEW_PERSPECTIVE_TEXT,
    NEW_THESIS_TEXT,
    NEW_THESIS_OPINION,
    NEW_THESIS_OPINION2,
    THESIS_TEXT,
    THESIS_OPINION,
    PREMISE_TEXT,
    PREMISE_IF_TRUE_WEIGHT,
    PREMISE_IF_FALSE_WEIGHT,
    PREMISE_OPINION,
    ;
}
